name: pull_request-opened-synchronize-reopened-event

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: aerius/github-actions/events/pull_request-event-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

