name: AERIUS

on:
  push:
  pull_request_target:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: aerius/github-actions/main-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
